<?php
// les passages de donnees   

//$_GET UTILKISE POUR LES LIENS , FILTRE ET AUSSI POUR LES RECHERCHES , LES DONNEES SONT PASSEE VIA L'URL 
// $_POST UTILIS LES FORMULAIRE  , DONNEE  VIA FORMULAIRE
// $_REQUEST COMBINE GET+ POST+ COOKIE utilisation generale( moins recommande)

//$_COOKIE  cookies  du navigateur , preferences , panier 
// $_SESSION VARIABLE DE SESSION, AUTHENTIFICATION , PANIER 

// $_FILES FICHIER UOLOADEE , IMAGE , DOCUMENTS

//$_SERVER INFORMNATTION DU SERVEUR , ULR, IP, METHODE HTTP


